### ISSUE TITLE
PHP7 Compatibility for lib/classes

### ISSUE THREAD

**Issue by tobiasreischmann** [gtn/exaport#13]
The classes within the files under lib/classes use the deprecated schema for class constructors.
Please replace these by __construct().
Thanks!

**Comment by Dagefoerde** [comment]
Dear maintainers,
I am sad to see that, so far, this issue has not received any attention at all in the past 6 months. I am well aware that – especially in open source projects – time is the most limiting factor, so I am far from demanding an immediate resolution :) . Nevertheless, it would be great if you could at least provide comments about possible compatibility issues and whether or how you plan on resolving them.

Anyway, we are in the process of upgrading our environment to PHP 7.1 and noticed that this issue still exists. Furthermore, I would like to point out another problem that becomes relevant as of PHP 7.1:
`lib/classes/element.inc.php` (https://github.com/gtn/exaport/blob/01586ea29fcca0118bceed3761aa4f5fa25cd94d/lib/classes/element.inc.php#L965):
`parent(...)` expects a parameter, but `remove()` calls it without one. As of PHP 7.1, this will throw an error (http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.too-few-arguments-exception).

As this does not seem to be your own code, but a third-party library, you think that you would rather fix the problems individually or would you rather upgrade the third-party library? (Is the latter even possible? :) )

Thank you!
