### ISSUE TITLE
Version 2024060600 - undefined functions in settings.php

### ISSUE THREAD

**Issue by turf212** [gtn/exaport#39]
lines 114 has

**block_exacomp_get_string**('settings_layout_settings_heading', 'block_exaport'),

and line 121 has

$settings->add(new block_exaport_layout_configtable('block_exaport_layout_settings', **block_exaport_get_string**(

which breaks installation or upgrade.  Changing these lines to just use get_string( fixes this.

**Comment by samuelcalegari** [comment]
Another problem on line  114 if block_exacomp is not installed :

Replace : 

// View custom template settings
$settings->add(new admin_setting_heading('exaport/layout_settings',
    block_exacomp_get_string('settings_layout_settings_heading', 'block_exaport'),
''));

by : 

// View custom template settings
$settings->add(new admin_setting_heading('exaport/layout_settings',
    get_string('settings_layout_settings_heading', 'block_exaport'),
''));

**Comment by qqtuyen** [comment]
version 
2024061300

is also having the same issue.

**Comment by dangerer** [comment]
done
