### ISSUE TITLE
Deprecated unserialize warning

### ISSUE THREAD

**Issue by ldgtd** [gtn/exaport#40]
**CONTEXT**
Moodle Workplace 4.1.13 (Build: 20240903)](https://moodle.com/workplace)
Plugin release version: 4.6.7 (Build: 2024072300)
PHP version: 8.1.28

**ISSUE**
`Deprecated: unserialize(): Passing null to parameter #1 ($data) of type string is deprecated in /var/www/html/blocks/exaport/lib/settings_helper.php on line 11`

Thank you for your work, best regard
L.

**Comment by dangerer** [comment]
done
